# Generated by Django 3.0.4 on 2020-03-12 06:09

from django.db import migrations, models
import hrm.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('experience', models.FloatField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=hrm.models.Users.upload_dir)),
                ('resume', models.ImageField(blank=True, null=True, upload_to=hrm.models.Users.upload_file)),
            ],
        ),
    ]
